import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Harmony Hive",
  description: "Generated by create next app",
};

import { getCurrentUser } from "@/lib/session";
export default async function RootLayout({ children }) {

  return (
    <html lang="en" className="h-full">
      <head />
      <body className={inter.className + " h-full"}>
        {children}
      </body>   
    </html>
  );
}
